version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dental_postgres_db
    restart: always
    environment:
      POSTGRES_DB: dental_clinic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: dental_django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=dental_clinic_db
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
    depends_on:
      - db

volumes:
  postgres_data: